# Config -----------------------------

name: Ariel Saldana
description: Blog about Ariel Saldana's work and CSS doodles
url: http://www.ariel.io

permalink: /:categories/:year/:month/:day/:title/

markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "autolink", "tables", "with_toc_data"]



# Some tests -----------------------------

# markdown: rdiscount
# rdiscount:
#   extensions:
#     - autolink      # greedily urlify links
#     - footnotes     # footnotes
#     - smart         # typographic substitutions with SmartyPants

#kramdown:
#  parse_block_html: true


# exclude: [archive, cursor-monster, letter-heads]
